package net.sf.l2j.gameserver.network.serverpackets;

import net.sf.l2j.gameserver.model.actor.Player;

public class GMViewCharacterInfo extends L2GameServerPacket {
    private final Player _activeChar;

    public GMViewCharacterInfo(Player character) {
        this._activeChar = character;
    }

    protected final void writeImpl() {
        writeC(143);
        writeD(this._activeChar.getX());
        writeD(this._activeChar.getY());
        writeD(this._activeChar.getZ());
        writeD(this._activeChar.getHeading());
        writeD(this._activeChar.getObjectId());
        writeS(this._activeChar.getName());
        writeD(this._activeChar.getRace().ordinal());
        writeD(this._activeChar.getAppearance().getSex().ordinal());
        writeD(this._activeChar.getClassId().getId());
        writeD(this._activeChar.getLevel());
        writeQ(this._activeChar.getExp());
        writeD(this._activeChar.getSTR());
        writeD(this._activeChar.getDEX());
        writeD(this._activeChar.getCON());
        writeD(this._activeChar.getINT());
        writeD(this._activeChar.getWIT());
        writeD(this._activeChar.getMEN());
        writeD(this._activeChar.getMaxHp());
        writeD((int) this._activeChar.getCurrentHp());
        writeD(this._activeChar.getMaxMp());
        writeD((int) this._activeChar.getCurrentMp());
        writeD(this._activeChar.getSp());
        writeD(this._activeChar.getCurrentLoad());
        writeD(this._activeChar.getMaxLoad());
        writeD(40);
        writeD(this._activeChar.getInventory().getPaperdollObjectId(16));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(2));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(1));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(3));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(5));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(4));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(6));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(7));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(8));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(9));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(10));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(11));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(12));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(13));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(7));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(15));
        writeD(this._activeChar.getInventory().getPaperdollObjectId(14));
        writeD(this._activeChar.getInventory().getPaperdollItemId(16));
        writeD(this._activeChar.getInventory().getPaperdollItemId(2));
        writeD(this._activeChar.getInventory().getPaperdollItemId(1));
        writeD(this._activeChar.getInventory().getPaperdollItemId(3));
        writeD(this._activeChar.getInventory().getPaperdollItemId(5));
        writeD(this._activeChar.getInventory().getPaperdollItemId(4));
        writeD(this._activeChar.getInventory().getPaperdollItemId(6));
        writeD(this._activeChar.getInventory().getPaperdollItemId(7));
        writeD(this._activeChar.getInventory().getPaperdollItemId(8));
        writeD(this._activeChar.getInventory().getPaperdollItemId(9));
        writeD(this._activeChar.getInventory().getPaperdollItemId(10));
        writeD(this._activeChar.getInventory().getPaperdollItemId(11));
        writeD(this._activeChar.getInventory().getPaperdollItemId(12));
        writeD(this._activeChar.getInventory().getPaperdollItemId(13));
        writeD(this._activeChar.getInventory().getPaperdollItemId(7));
        writeD(this._activeChar.getInventory().getPaperdollItemId(15));
        writeD(this._activeChar.getInventory().getPaperdollItemId(14));
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeH(0);
        writeD(this._activeChar.getPAtk(null));
        writeD(this._activeChar.getPAtkSpd());
        writeD(this._activeChar.getPDef(null));
        writeD(this._activeChar.getEvasionRate(null));
        writeD(this._activeChar.getAccuracy());
        writeD(this._activeChar.getCriticalHit(null, null));
        writeD(this._activeChar.getMAtk(null, null));
        writeD(this._activeChar.getMAtkSpd());
        writeD(this._activeChar.getPAtkSpd());
        writeD(this._activeChar.getMDef(null, null));
        writeD(this._activeChar.getPvpFlag());
        writeD(this._activeChar.getKarma());
        int _runSpd = this._activeChar.getStat().getBaseRunSpeed();
        int _walkSpd = this._activeChar.getStat().getBaseWalkSpeed();
        int _swimSpd = this._activeChar.getStat().getBaseSwimSpeed();
        writeD(_runSpd);
        writeD(_walkSpd);
        writeD(_swimSpd);
        writeD(_swimSpd);
        writeD(0);
        writeD(0);
        writeD(this._activeChar.isFlying() ? _runSpd : 0);
        writeD(this._activeChar.isFlying() ? _walkSpd : 0);
        writeF(this._activeChar.getStat().getMovementSpeedMultiplier());
        writeF(this._activeChar.getStat().getAttackSpeedMultiplier());
        writeF(this._activeChar.getCollisionRadius());
        writeF(this._activeChar.getCollisionHeight());
        writeD(this._activeChar.getAppearance().getHairStyle());
        writeD(this._activeChar.getAppearance().getHairColor());
        writeD(this._activeChar.getAppearance().getFace());
        writeD(this._activeChar.isGM() ? 1 : 0);
        writeS(this._activeChar.getTitle());
        writeD(this._activeChar.getClanId());
        writeD(this._activeChar.getClanCrestId());
        writeD(this._activeChar.getAllyId());
        writeC(this._activeChar.getMountType());
        writeC(this._activeChar.getStoreType().getId());
        writeC(this._activeChar.hasDwarvenCraft() ? 1 : 0);
        writeD(this._activeChar.getPkKills());
        writeD(this._activeChar.getPvpKills());
        writeH(this._activeChar.getRecomLeft());
        writeH(this._activeChar.getRecomHave());
        writeD(this._activeChar.getClassId().getId());
        writeD(0);
        writeD(this._activeChar.getMaxCp());
        writeD((int) this._activeChar.getCurrentCp());
        writeC(this._activeChar.isRunning() ? 1 : 0);
        writeC(321);
        writeD(this._activeChar.getPledgeClass());
        writeC(this._activeChar.isNoble() ? 1 : 0);
        writeC(this._activeChar.isHero() ? 1 : 0);
        writeD(this._activeChar.getAppearance().getNameColor());
        writeD(this._activeChar.getAppearance().getTitleColor());
    }
}
